name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]  # Only run after CI succeeds
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install -r requirements/prod.txt
        
    - name: Build Docker image
      run: docker build -t deepseek-coder:latest .
      
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag deepseek-coder:latest ${{ secrets.DOCKER_HUB_USERNAME }}/deepseek-coder:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/deepseek-coder:latest
        
    - name: Deploy to staging
      if: github.ref == 'refs/heads/main'
      run: bash scripts/deploy.sh staging
      
    - name: Deploy to production
      if: startsWith(github.ref, 'refs/tags/v')
      run: bash scripts/deploy.sh production
