name: CI (Full)
on:
  schedule:
    - cron: "0 0 * * *"  # Daily
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - run: bash scripts/download_model.sh
      - run: pip install -r requirements/dev.txt
      - run: bash scripts/run_tests.sh
